language: python
dist: trusty
sudo: required

python:
  - 2.7
  - 3.6

env:
  - DB=mariadb
  - DB=postgres
  - TEST_TYPE=ui

services:
  - mysql

addons:
  postgresql: "9.5"
  hosts:
    - test_site
    - test_site_postgres
    - test_site_ui

matrix:
  exclude:
  - python: 2.7
    env: DB=postgres
  - python: 2.7
    env: TEST_TYPE=ui

install:
  - $TRAVIS_BUILD_DIR/.travis/install.sh

before_script:
  - cd ~/frappe-bench
  - sed -i 's/9000/9001/g' sites/common_site_config.json
  - bench start &
  - sleep 10

script:
  - $TRAVIS_BUILD_DIR/.travis/run-tests.sh

after_script:
  - coveralls -b apps/frappe -d ../../sites/.coverage